// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	model "jpnovelmtlgo/internal/model"

	mock "github.com/stretchr/testify/mock"

	request "jpnovelmtlgo/internal/model/request"

	response "jpnovelmtlgo/internal/model/response"
)

// KakuyomuService is an autogenerated mock type for the KakuyomuService type
type KakuyomuService struct {
	mock.Mock
}

// KakuyomuChapterPage provides a mock function with given fields: params
func (_m *KakuyomuService) KakuyomuChapterPage(params *request.ChapterNovelRequest) (*model.BaseResponse[*response.GetChapterPageResponse], error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for KakuyomuChapterPage")
	}

	var r0 *model.BaseResponse[*response.GetChapterPageResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(*request.ChapterNovelRequest) (*model.BaseResponse[*response.GetChapterPageResponse], error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*request.ChapterNovelRequest) *model.BaseResponse[*response.GetChapterPageResponse]); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BaseResponse[*response.GetChapterPageResponse])
		}
	}

	if rf, ok := ret.Get(1).(func(*request.ChapterNovelRequest) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KakuyomuListChapter provides a mock function with given fields: params
func (_m *KakuyomuService) KakuyomuListChapter(params *request.ChapterNovelRequest) (*model.BaseResponse[[]request.TranslateListRequest], error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for KakuyomuListChapter")
	}

	var r0 *model.BaseResponse[[]request.TranslateListRequest]
	var r1 error
	if rf, ok := ret.Get(0).(func(*request.ChapterNovelRequest) (*model.BaseResponse[[]request.TranslateListRequest], error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(*request.ChapterNovelRequest) *model.BaseResponse[[]request.TranslateListRequest]); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BaseResponse[[]request.TranslateListRequest])
		}
	}

	if rf, ok := ret.Get(1).(func(*request.ChapterNovelRequest) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewKakuyomuService creates a new instance of KakuyomuService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKakuyomuService(t interface {
	mock.TestingT
	Cleanup(func())
}) *KakuyomuService {
	mock := &KakuyomuService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
